name: thesis
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - matplotlib
  - numpy
  - jupyterlab
  - scikit-learn
  - pandas
  - uvicorn
  - fastapi